# These are supported funding model platforms

github: ['kennedy-ex', 'riz-ex', 'aryazakaria01', 'FeriEXP', 'sip-userbot']
community_bridge: kennedy-project
custom: ['https://t.me/suportNande', 'https://t.me/suportsipuserbot']
